### ISSUE TITLE
Unexpected behavior for gsHistogram

### ISSUE THREAD

**Issue by federicomarini** [AnnekathrinSilvia/GeDi#14]
```
gs_names <- c("a", "b", "c", "d", "e", "f", "g", "h", "i")
genesets <- list(
  c("PDHB", "VARS2"), c("IARS2", "PDHA1"),
  c("AAAS", "ABCE1"), c("ABI1", "AAR2"), c("AATF", "AMFR"),
  c("BMS1", "DAP3"), c("AURKAIP1", "CHCHD1"), c("IARS2"),
  c("AHI1", "ALMS1")
)

p <- gsHistogram(genesets, gs_names)
p
```

gives me 
<img width="822" alt="image" src="https://github.com/AnnekathrinSilvia/GeDi/assets/7447478/305bc6f0-43d5-44af-a6f0-2543d6b44765">

**Comment by AnnekathrinSilvia** [comment]
Seems to be solved with this commit https://github.com/AnnekathrinSilvia/GeDi/commit/c21a5a565b5f4e65e297dc3851e626ec2ce97ade

**Comment by federicomarini** [comment]
We can safely close this one I would say 😉
