### ISSUE TITLE
Unable to download PPI matrix

### ISSUE THREAD

**Issue by NajlaAbassi** [AnnekathrinSilvia/GeDi#15]
Data Input Panel: when I try to use the button to download the PPI Matrix the app exists and throws the following warning
```
Warning in download.file(urlStr, temp) :
  URL https://stringdb-downloads.org/download/protein.aliases.v11.5/9606.protein.aliases.v11.5.txt.gz: cannot open destfile '/Users/abassina/Library/Caches/org.R-project.R/R/GeDi/9606.protein.aliases.v11.5.txt.gz', reason 'No such file or directory'
Warning in download.file(urlStr, temp) :
  download had nonzero exit status
Warning: Error in if: missing value where TRUE/FALSE needed
```
also the link for STRING in step2 doesn't work

**Comment by AnnekathrinSilvia** [comment]
Solved this, the error was that the cache folder was never created so on machines without this folder the code initially crashed. Now the folder is generated if it does not exist beforehand.
