### ISSUE TITLE
Distance Score Heatmap never shows inside the app

### ISSUE THREAD

**Issue by NajlaAbassi** [AnnekathrinSilvia/GeDi#16]
I wanted to visualize the heatmap for different distance scores, waited for forever but it's never displayed in the app. However, it is there in the final html report.
I also got an aborted session a couple of times, specifically when using the **GO similarity scores**, but it was at random times

<img width="1051" alt="Screenshot 2024-03-08 at 11 36 39" src="https://github.com/AnnekathrinSilvia/GeDi/assets/112277365/21dacf0f-7630-4d51-a143-46eb3624d16b">
<img width="1182" alt="Screenshot 2024-03-08 at 11 38 31" src="https://github.com/AnnekathrinSilvia/GeDi/assets/112277365/ba99933e-1bb3-4cd8-9448-7fb717c43ab0">
<img width="727" alt="Screenshot 2024-03-08 at 09 29 59" src="https://github.com/AnnekathrinSilvia/GeDi/assets/112277365/d713ebf5-e195-46af-8de6-c8957ebfd6cf">

**Comment by AnnekathrinSilvia** [comment]
I seem to have fixed the first issue with the not displayed heatmap with commit https://github.com/AnnekathrinSilvia/GeDi/commit/d6a2d66dabcc1fdf16da1163c4b9a065656d0844
